version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase
    open-pull-requests-limit: 10

    schedule:
      interval: daily
      timezone: Asia/Jakarta
      time: 07:00

    assignees:
      - manferlo81

    groups:
      lint:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - eslint
          - "@eslint/*"
          - "@*/eslint-plugin"
          - eslint-plugin-*
          - eslint-*
          - typescript-eslint
          - globals

      test:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - jest
          - ts-jest
          - "@types/jest"

      types:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - "@types/*"
          - typescript

      babel:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - "@babel/*"
          - core-js

      others:
        dependency-type: development
        update-types:
          - minor
          - patch
