version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase
    open-pull-requests-limit: 10

    schedule:
      interval: "daily"
      timezone: "Asia/Jakarta"
      time: "07:00"

    groups:
      lint:
        dependency-type: development
        patterns:
          - eslint
          - eslint-plugin-*
          - "*eslint-plugin"
          - globals
      types:
        dependency-type: development
        patterns:
          - "@types/*"
      jest:
        dependency-type: development
        patterns:
          - jest
      babel:
        dependency-type: development
        patterns:
          - "@babel"
          - core-js
      others:
        dependency-type: development
        patterns:
          - husky
          - npm-run-all
          - rimraf
          - chokidar

    assignees:
      - "manferlo81"
