version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase
    open-pull-requests-limit: 10

    schedule:
      interval: "daily"
      timezone: "Asia/Jakarta"
      time: "07:00"

    assignees:
      - "manferlo81"

    groups:
      lint:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - eslint
          - globals
          - typescript-eslint
          - "@eslint/*"
          - eslint-plugin-*
          - "@*/eslint-plugin"
          - eslint-*

      types:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - "@types/*"

      test:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - jest
          - ts-jest

      babel:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - "@babel/*"
          - core-js

      others:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - husky
          - npm-run-all
          - rimraf
          - chokidar
